### ISSUE TITLE
Add music support

### ISSUE THREAD

**Issue by Justiphi** [Justiphi/Tatenashi#2]
I would like music commands to be added, a new service file should be added in the Services file and the commands should be added in the Services folder and commands should be added to the Modules/Music/AudioModule.cs file.

Music should be streamable rather than downloading files.
ffmpeg, libsodium and youtube.dll have already been added to the repository.

**Comment by brogowski** [comment]
I can take this one but I had hard time to make bot react to `Music` command.

Can you give me some hints how to setup it so I can test my solution?

**Comment by Justiphi** [comment]
Hi @brogowski 
in order to setup the bot for testing you will need a file in the root directory of the project called '_config.json'
this file is used by the configuration service to provide necessary keys and connection strings in order to start the bot, the current contents of the file is as follows:
`
{
  "Token": "Discord Bot Token",
  "ConnectionString": "mySQL connection string"
}
`
the database will create itself upon initial startup as long as a valid connection string is present and you will have to run the command '+perms music enable' to use the commands in the audiomodule.cs file, hope this helps.

**Comment by brogowski** [comment]
Thanks for help, I've managed to make it work with youtube-dl - please look at #20

**Comment by Justiphi** [comment]
I have tested and merged the code, I will probably add the ability to use playlists and search terms with it in the future but it works far better and more stable than the old music code I used to use. Thank you.
