### ISSUE TITLE
Hacktoberfest: Add new Commands to bot

### ISSUE THREAD

**Issue by Justiphi** [Justiphi/Tatenashi#4]
Create your own command for the Tatenashi Discord bot!

Commands should be added to the Modules/Hacktoberfest/Hacktoberfest.cs file.

A commented template has been provided for commands.

**Comment by renato04** [comment]
I would like to do this

**Comment by jotaro-sama** [comment]
Hi! I added mine in #7

**Comment by jotaro-sama** [comment]
Hi! I created mine in #7

**Comment by renato04** [comment]
Hello! I opened a PR for my command

**Comment by Justiphi** [comment]
Thank you to those who have submitted commands so far @renato04 @jotaro-sama @ertugrulk @zez9787 and @yoshivb 
Tatenashi Hacktoberfest update 1 is now live, the new commands added are:

1. +Hackfest MonthLength <monthNumber>
2. +Hackfest RollSixDice
3. +Hackfest PalindromeCheck <word>
4. +Hackfest YouTubeSearch <searchTerm>
5. +Hackfest Urban <searchTerm>
6. +Hackfest FantasyName

Looking forward to seeing more commands as they come in, keep up the amazing work!

**Comment by Justiphi** [comment]
Thank you to all those who submitted commands for hacktoberfest, I will be updating the bot over the next couple days so all commands will be live by the end of the week.
